namespace cimbar {
static const std::map<std::string, std::string> bitmaps = {
{"bitmap/4/00.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAHbCw`Xax=HiUBFC'Ki?(%|B'TrhDs'$U1S};@S+i&AkC0kN!$jlx@ttqL7vzB~T[E'=HzKr1R16AAAXLhYKMe8#(\C)"},
{"bitmap/4/01.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA'aCw`XaxEy!~B'B'1'ItdE[hFB)O$GgENdlNsoXb61gQ.oZ)@A9HN8ZLJGSD,2AA*~(vT44!NFAAAA_cE3Y@%LfDC)"},
{"bitmap/4/02.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA]aCw`XaxEy\~B'B'1'ItlE[hFB)OeMgENd8YsoXb5IhQ.oZ)@A9HN8.\%2.4IANp}~l%:x]5JAAAdZJzDwHP_Q%)"},
{"bitmap/4/03.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA6aCw`Xax4{NUVGC'wA11P~?o=B63@$|a.RAJ{FDFOfK-~.9JjE4ng|4L[LT7c*U/R)Zy|AAAuW&wUY6eit&F)"},
{"bitmap/4/04.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAdZCw`XaxEyVE:':vZLgxdEEAL7VxnT\M$BUA}?.AO{-NHLIX\cBAAAfza@AM+D(aQ)"},
{"bitmap/4/05.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAXbCw`XaxK$vR'EC'DXF%A'ZSHl-F4xV&R0ww%Zr5t7ElK+{gF2/C=Ep1]3\3nc*:f{(H2b:v'~&-MAAAAAr7vbMo\F9BB)"},
{"bitmap/4/06.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA3bCw`Xax=HvRBFC'DXf7B'0x-[igTz|0L!c#F=pX6y,n*awZr3/^qUE4Wv.dW@;Kn};+Md;K`ayA&t]`d[OAAAdZJzDwHP_Q%)"},
{"bitmap/4/07.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAaaCw`XaxEyVE:':vZLgxdEEAEY_mxZPzmxK\c4qTZbLiUtw%GB4kCA0-wD=J+PO.AAAA=5GUv+oX!GE)"},
{"bitmap/4/08.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA]aCw`Xax4{uR:EBtHu~19|?Q|g9PQM3l;A;Ef+GN&lZFJuVk4Bh*=]$r5}PPdESH:xgGyNOtLAAAXLhYKMe8#(\C)"},
{"bitmap/4/09.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAaaCw`XaxEy\~B'B'1'It*$^($Y7RO8x(]W9Aw/6ZUgVEzWqX=doIAApR|v\owQtQAAAA=5GUv+oX!GE)"},
{"bitmap/4/0a.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA9ZCw`XaxEy\~B'B'1'ItGRpn$Lw/zWpN'o%t|tiKcXRHAA0y]_act9/HAAAA(d*NH%_C=t)"},
{"bitmap/4/0b.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAqaCw`XaxEy\~B'B'zA:hgM;I.(KCdLgxdEEAR5x(aW2-4kOc+i;z[WTAw$FX|(=r,NDAAA8Mz+BYxHr1g)"},
{"bitmap/4/0c.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAiaCw`XaxEy!~B'B'1'/\B'B'ZSK1Oi&a37DTovt'Hbl%|W02+22!VAv(^0s=Ed0;/BAAC'nHpwZ9)'&F)"},
{"bitmap/4/0d.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAHbCw`XaxEyVEXH__B'B'ZSxtVEbjgMCzn'|2![wW12+[wW`_HT;[wuZP3ekg6EnAk_74t+)d6\iCAAC'nHpwZ9)'&F)"},
{"bitmap/4/0e.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA:aCw`XaxEyVENB4FGt~.-oG5QBZ!ozmxbj0w.\\My8'Sr?[B)Oyw(WU~[hFBF'\OCjjHmUuRAAAAr7vbMo\F9BB)"},
{"bitmap/4/0f.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAyaCw`XaxEylE:'B'B'5y`V;I3+pN#F*hDTRkgMO?(N#NJ1$LvNu2]b`=AARK{Xmn89zcAAAA_cE3Y@%LfDC)"},
{"bitmap/anchor-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAAskCw`Xg#A$mr2Dmu1X~4C*~sns0GV]=CYS#olfs)j'~4i8n5Rja=Ytlm5slR:K~%Re)(F-S:Diz*Xqr{NUwa{;Bk?S-GK)OSFpFE@:M:iVE7===wt=CmK]BRxEZ3j6H)OSFpv1YC7.S:DiHJwU*aNu{pf_E{\r~v.?Qi*aNuRIC?`8EzH`I@Qi*aNuRIC?%|Z:Y$Z4U!g~lh1lJAAAuW&wUY6eit&F)"},
{"bitmap/anchor-light.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAA_kCw`Xg#A$?UPF$AO5sc?_B'29saGT,H|Ur0xDcVZID6t;$O}@TspIvaOXvO4`D`^#5+#2)EZ3j6rgZ1L4P~'`?gle{?Qi*aNuRIC?'8XK\[+jB_Zj9NSudkK]BRxEZ3j6H)OSFpv1YC7.S:DiHJwU*aY=f$j(OqiS#2)EZ3j6rg`%'0A}J@#2)EZ3j6rgw$X6!^2VCP-G3l/(]`!tV07AAABtnHpwZ9)'&F)"},
{"bitmap/anchor-secondary-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAAkkCw`Xg#A$mr+DpB`X~4HQ@~?QkxPv,Fiu%;Yj)E5/00wypzzSx^D4G\~nGi)!8[AesS&uCRxE+gFCvgFO)~v~Xgb60^Qi*aNudkK]BRxEZ3j6N:Y6op2TZ|k$\#%uCRxEZ3j6H)OSFpv1oyOgRLGbp^Qi*aNudkK]BRxEZ3j6N:XNXhwqibiC7.S:`gbP%,q!3CwE2v/&kEzWAAAA=5GUv+oX!GE)"},
{"bitmap/anchor-secondary-light.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAA-kCw`Xg#A$?U'ElB+B~42)~s?ig#6uKOY^SeM!#zs5al&ls^&y?sx'A9NLY0gWRy8;+L*mBTFpv1[nS9dW=.H]B\6K&x%uCRxEZ3j6H)OSFpv1%XLQk;xhvn]p|w%uCRxEZ3j6H)OSFpv1waXgUy$N`$F-S:DiHJwU*aNudkK]h#5GXWYV-GK)OSFpFEb~K:*rh$\FmDEBUwmw:c=SmlAAAA=5GUv+oX!GE)"},
{"bitmap/guide-horizontal-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAA6yBAC'5FMAAAR9S,$BAAdZ=J.!wCC'\vBAVBWBP%tvNAAA$YCw`XJ0Cy\~B'B'di~haCJlf^Vxa4CAmy4B|;F4_RBAAA9ZNoBz[uhNI)"},
{"bitmap/guide-horizontal-light.png", R"(vuk:eJs4+BAAN/-MCG4DAA6yBAC'5FMAAAR9S,$BAAdZ=J.!wCC'\vBAVBWBP%tvNAAA$YCw`XJ0CylE[h_sbxWEaAdCTFeO+OAA_cYtpIKWUOAAAA=5GUv+oX!GE)"},
{"bitmap/guide-vertical-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAA:CAAAA]FMAAAs8KD,IAAdZ=J.!wCC'\vBAVBWBP%tvNAAAFZCw`XJ0Cy\~B'B'0tVE[hHB~hpx+RJ,pVZA|;DV-vzcLWKBAABtnHpwZ9)'&F)"},
{"bitmap/guide-vertical-light.png", R"(vuk:eJs4+BAAN/-MCG4DAA:CAAAA]FMAAAs8KD,IAAdZ=J.!wCC'\vBAVBWBP%tvNAAA}YCw`XJ0CylE[h_s{Qxt(aNtXxnR(*@I`NDAqv9(Xu`EEAAAAAr7vbMo\F9BB)"},
};
}
