namespace cimbar {
static const std::map<std::string, std::string> bitmaps = {
{"bitmap/4/00.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA&aCw`XaxEylEB'B'atItc|3|y|UAp!E8e+_GyD?^VR_3wcW'Qh#GAaztVEMA`*8DBfF/k8AAAA9ZNoBz[uhNI)"},
{"bitmap/4/01.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA]aCw`Xax=HOU:EBtV)%tL-IV&7RD,W?p/]fZO-8B$}Fhjf%GC}~Y8(/Y$w|t^oN/ZNiN0s}\5AAAuW&wUY6eit&F)"},
{"bitmap/4/02.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA]aCw`Xax4{NUBFBt&t%tk`B'H{1N6k{N,,B$ho#%7F'Su&HLs]iDkfwcgZSGR501W0WE+WxodAAAuW&wUY6eit&F)"},
{"bitmap/4/03.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA'aCw`Xax4{NUWGC'Ki?($[.Vk~Mw/(Vi|NaT&N6S!Z/oaW/o\9F-6}_UbXy:pB}A{4/A0(]PciAAAA_cE3Y@%LfDC)"},
{"bitmap/4/04.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAaaCw`XaxEy\~B'B'zA:hI0mgUE[h!G=C5F_AzIpYu+eM:GP^t/AyEA6}cu6:4fVWAAAA=5GUv+oX!GE)"},
{"bitmap/4/05.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA3bCw`XaxJTvR3DC'ai\!!~?Q/K&u:Ihr=k[CmZ^tc74&_pS16y?}w(e2A(kb_Ug0kId-N)|2Pjb$6Cq@`8NAAA6yQMFGPe=hnB)"},
{"bitmap/4/06.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA#bCw`Xax=HvR'EC'DX)_A'MJe7fGx+xz9fO!vadv&):zQ*Wy/[.@mw%,DZK?]yTayU_=[o;%oNaMmC?`6^2yAAAA=5GUv+oX!GE)"},
{"bitmap/4/07.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAHbCw`Xax=HnR'EAA?W=['~ZSw*NReO=a7#Y$)DW=%MX]VJschDxl0)eGxlG{4#2S4M1X#ydhP]kEAAAA?O@GxgqB_W)"},
{"bitmap/4/08.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAPbCw`XaxEylEB'B'.(KC!}MBbB`(CiHH*6.\lXB?\+bPNv3W2(,GVLaH%=hiRQ4(AAs8,UoY=&$BFAAAdZJzDwHP_Q%)"},
{"bitmap/4/09.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA'aCw`XaxEylEB'B'atIt*$._E%W'~?~tM[0tVEIMyq|9Pzs8Lv\hHH%mln=kbHBA3|duUVX5/8AAAA=5GUv+oX!GE)"},
{"bitmap/4/0a.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA]aCw`XaxEylEB'B'atIt+~.(KCtdiN$Ia67PQIl%XR%g;C#Bx?]AbN2eggTtBAo.rugwO$ofdAAA6yQMFGPe=hnB)"},
{"bitmap/4/0b.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAiaCw`XaxEylEB'B'b'x(CiJBDtdEEAR56}mz9~x2.\kD5yjG5y[B&C+\2PlZ001+&AAAC'nHpwZ9)'&F)"},
{"bitmap/4/0c.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAqaCw`XaxEylEB'B'X4};pI.(KCR?CKdt~QO*,=bP\WUtfdIw8DV/!y]B0k}0~Fok*2lAAAXLhYKMe8#(\C)"},
{"bitmap/4/0d.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAnbCw`Xax4{uR3DAA?WHb|~\jg1\Fw+ij&M[M.THhSA#;=+&1iDl3`vvOZik1@iRjSnl2eBlVXEE!^so1AAAA9ZNoBz[uhNI)"},
{"bitmap/4/0e.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAAnbCw`XaxEy\~B'B'1'z(OO21/1Xbw+&a5N{~!eggL*zHiC!u\g`p=\o'7w6iS/bWrI,(AA,9:BMOC7XMAAAA=5GUv+oX!GE)"},
{"bitmap/4/0f.png", R"(vuk:eJs4+BAAN/-MCG4DAAXLAAAA7FMAAA_)z_ZMAAdZ=J.!wCC'\vBAVBWBP%tvNAAA'aCw`XaxEy\~B'B'zA:hJB~(ZSxt(ajLv(AmX~8Z:GjDbP2!jRw2.\&JY.{N7NAA7*wB{2YGO7AAAA=5GUv+oX!GE)"},
{"bitmap/anchor-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAAskCw`Xg#A$mr2Dmu1X~4C*~sns0GV]=CYS#olfs)j'~4i8n5Rja=Ytlm5slR:K~%Re)(F-S:Diz*Xqr{NUwa{;Bk?S-GK)OSFpFE@:M:iVE7===wt=CmK]BRxEZ3j6H)OSFpv1YC7.S:DiHJwU*aNu{pf_E{\r~v.?Qi*aNuRIC?`8EzH`I@Qi*aNuRIC?%|Z:Y$Z4U!g~lh1lJAAAuW&wUY6eit&F)"},
{"bitmap/anchor-light.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAA_kCw`Xg#A$?UPF$AO5sc?_B'29saGT,H|Ur0xDcVZID6t;$O}@TspIvaOXvO4`D`^#5+#2)EZ3j6rgZ1L4P~'`?gle{?Qi*aNuRIC?'8XK\[+jB_Zj9NSudkK]BRxEZ3j6H)OSFpv1YC7.S:DiHJwU*aY=f$j(OqiS#2)EZ3j6rg`%'0A}J@#2)EZ3j6rgw$X6!^2VCP-G3l/(]`!tV07AAABtnHpwZ9)'&F)"},
{"bitmap/anchor-secondary-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAAkkCw`Xg#A$mr+DpB`X~4HQ@~?QkxPv,Fiu%;Yj)E5/00wypzzSx^D4G\~nGi)!8[AesS&uCRxE+gFCvgFO)~v~Xgb60^Qi*aNudkK]BRxEZ3j6N:Y6op2TZ|k$\#%uCRxEZ3j6H)OSFpv1oyOgRLGbp^Qi*aNudkK]BRxEZ3j6N:XNXhwqibiC7.S:`gbP%,q!3CwE2v/&kEzWAAAA=5GUv+oX!GE)"},
{"bitmap/anchor-secondary-light.png", R"(vuk:eJs4+BAAN/-MCG4DAAk_AAAA.FMAAAkUJ/IKAAdZ=J.!wCC'\vBAVBWBP%tvNAAA-kCw`Xg#A$?U'ElB+B~42)~s?ig#6uKOY^SeM!#zs5al&ls^&y?sx'A9NLY0gWRy8;+L*mBTFpv1[nS9dW=.H]B\6K&x%uCRxEZ3j6H)OSFpv1%XLQk;xhvn]p|w%uCRxEZ3j6H)OSFpv1waXgUy$N`$F-S:DiHJwU*aNudkK]h#5GXWYV-GK)OSFpFEb~K:*rh$\FmDEBUwmw:c=SmlAAAA=5GUv+oX!GE)"},
{"bitmap/guide-horizontal-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAA6yBAC'5FMAAAR9S,$BAAdZ=J.!wCC'\vBAVBWBP%tvNAAA$YCw`XJ0Cy\~B'B'di~haCJlf^Vxa4CAmy4B|;F4_RBAAA9ZNoBz[uhNI)"},
{"bitmap/guide-horizontal-light.png", R"(vuk:eJs4+BAAN/-MCG4DAA6yBAC'5FMAAAR9S,$BAAdZ=J.!wCC'\vBAVBWBP%tvNAAA$YCw`XJ0CylE[h_sbxWEaAdCTFeO+OAA_cYtpIKWUOAAAA=5GUv+oX!GE)"},
{"bitmap/guide-vertical-dark.png", R"(vuk:eJs4+BAAN/-MCG4DAA:CAAAA]FMAAAs8KD,IAAdZ=J.!wCC'\vBAVBWBP%tvNAAAFZCw`XJ0Cy\~B'B'0tVE[hHB~hpx+RJ,pVZA|;DV-vzcLWKBAABtnHpwZ9)'&F)"},
{"bitmap/guide-vertical-light.png", R"(vuk:eJs4+BAAN/-MCG4DAA:CAAAA]FMAAAs8KD,IAAdZ=J.!wCC'\vBAVBWBP%tvNAAA}YCw`XJ0CylE[h_s{Qxt(aNtXxnR(*@I`NDAqv9(Xu`EEAAAAAr7vbMo\F9BB)"},
};
}
